version: '3'
services:
  app:
    build:
      context: ./
    depends_on: 
      - database
    image: n-app
    container_name: n-app
    ports:
      - 3000:5000
    environment:
      PORT: 5000
      DB_USER: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: test_db
    # command: tail -f /dev/null #テスト

  database:
    image: postgres:12.3
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: test_db
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust
